Fix/timeout fix 2
ebi-ait/ingest-exporter pull request #16
Opened 2021-03-05 10:19 UTC by jacobwindsor

Fixes [#191](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/191).

This just increases the maximum total wait time for a data export job and also limits the wait time to increasing to more than 10 minutes.

This relates to #15. We decided to go with this simple approach since the Pub/Sub for transfer documentation is not the best and we're not sure how it will behave with multiple instances of exporter.

2021-03-05 11:02 UTC, aaclan-ebi submitted a review, later dismissed
Good call on switching to this approach. It's simpler and this should solve the timeout issue! Sorry if I suggested a very big change, we can still work on using it when we have more time so those efforts shouldn't be wasted! Thanks for the hard work on that.

2021-03-05 11:02 UTC, aaclan-ebi commented on exporter/terra/gcs.py
> +                    new_wait_time = min(wait_time * 2, 10 * 60)
Could comment here the quota we know at this time and put the doc link. Might be useful for someone in the future trying to understand why we pick this wait time.

GET /transferJob has a quota of 500 requests every 100 seconds
https://cloud.google.com/storage-transfer/quotas

2021-03-05 11:02 UTC, aaclan-ebi commented on exporter/terra/gcs.py
>          if time_waited > max_wait_time_secs:
would be nice to handle this error when it's propagated to DcpStagingClient and report a submission error so somehow we'll know without having to check the logs.

Something similar to the importer error:  https://github.com/ebi-ait/ingest-client/blob/master/ingest/importer/importer.py#L71

Could be in a later change when we improve the exporter's error handling. Six hours should have greatly lessen the chance of this timeout happening anyways.

2021-03-05 13:59 UTC, jacobwindsor commented on exporter/terra/gcs.py
> +                    new_wait_time = min(wait_time * 2, 10 * 60)
Done but put in assert_job_complete

2021-03-05 14:06 UTC, jacobwindsor commented on exporter/terra/gcs.py
>          if time_waited > max_wait_time_secs:
Yeah I think this should be in a later change. Exporter error handling is not great anyway

2021-03-09 10:54 UTC, amnonkhen requested changes

2021-03-09 10:54 UTC, amnonkhen commented on exporter/terra/gcs.py
> +        return self._assert_job_complete(job_name, 2, 0, six_hours_in_seconds)
I would create constants or use named params for the `2` and `0`

2021-03-09 13:06 UTC, amnonkhen commented on exporter/terra/gcs.py
> +        return self._assert_job_complete(job_name, wait_time_seconds, time_waited_seconds, max_wait_time_seconds)
Have you considered using named parameters:

```python
return self._assert_job_complete(self, 
          job_name, 
          wait_time=2, 
          time_waited=0, 
          max_wait_time_secs=60 * 60 * 6):
```

In addition, it would be possible to define the 2 and 60*60*6 as constants.

2021-03-09 13:07 UTC, amnonkhen approved these changes
Approved.
Please read my last comment. regarding named params.

2021-03-09 13:10 UTC, aaclan approved these changes

2021-03-09 13:12 UTC, aaclan-ebi approved these changes

2021-03-09 13:19 UTC, merged