Fix rate limit error ebi-ait/dcp-ingest-central#289
ebi-ait/ingest-exporter pull request #24
Opened 2021-05-11 15:04 UTC by aaclan-ebi

ebi-ait/dcp-ingest-central#289

Main logic change :

Only the exporter process which is successful to create the data transfer job should be polling GCP to check if the job is complete. Other processes will check the isDataTransferComplete flag in the export job context info from Ingest Core.
This is to avoid hitting the GCP rate limit 500 requests per 100 sec https://cloud.google.com/storage-transfer/quotas

I tested with a submission using the dataset which has 897 assay processes where this issue has occured. The error is not consistently being replicated before the change but I've done several runs and the error hasn't happened again yet so far. In theory, this should greatly reduce the requests we're sending to GCP.

2021-05-14 15:34 UTC, MightyAx approved these changes
I don't feel I can meaningfully review the code but I'm confident in your methods based on the testing and our discussion earlier.

I hada question, but my approval is not contingent upon you answering it.

2021-05-14 15:34 UTC, MightyAx commented on exporter/terra/terra_listener.py
> +        return [experiment_consumer]
this method still returns a list of consumers, but that list will always be of length 1.
Should the signature/name change here to `def get_consumer(...) -> Consumer:`

2021-05-17 15:40 UTC, jacobwindsor approved these changes
Yeah much better. Thanks!

2021-05-17 15:46 UTC, amnonkhen requested changes

2021-05-17 15:46 UTC, amnonkhen commented on exporter/terra/dcp_staging_client.py
>          bucket_and_key = self.bucket_and_key_for_upload_area(upload_area)
instead of populateing an array and derefrencing by index, you could populate 2 variables:

```python
bucket, key = ...
```

2021-05-17 15:48 UTC, amnonkhen approved these changes

2021-05-18 14:07 UTC, merged