Added logging of export time in milliseconds
ebi-ait/ingest-exporter pull request #25
Opened 2021-09-24 10:52 UTC by aaclan-ebi

2021-09-29 08:51 UTC, amnonkhen requested changes

2021-09-29 08:51 UTC, amnonkhen commented on exporter/terra/terra_listener.py
> +            start_time = datetime.datetime.now()
A much cleaner and reusable approach would be to add a timing decorator to `terra_exporter.export()`

2021-10-01 12:16 UTC, jacobwindsor reviewed
Does this log the UUID with the export time? No right? I think it would be useful to have project/submission on all log messages from the exporter

2021-10-01 12:22 UTC, aaclan-ebi commented
@jacobwindsor yes, it logs the function parameters and  submission UUID and project UUID is there. 
> it would be useful to have project/submission on all log messages from the exporter
could be in a separate ticket/PR

2021-10-01 12:39 UTC, ke4 approved these changes
👍

2021-10-01 12:39 UTC, ke4 commented on exporter/terra/terra_listener.py
> +import datetime
I believe this import is not used

2021-10-01 12:49 UTC, jacobwindsor approved these changes

2021-10-01 15:21 UTC, merged

2021-10-01 15:26 UTC, aaclan-ebi commented
I forgot to set the target branch to dev so I've merged the branch separately thru the command line.